### SERVER
@HOST = http://localhost:8080
@VERSION = /api/
@SERVER = {{HOST}}{{VERSION}}


### GET ALL POKEMONS
GET {{SERVER}}pokemon


### GET POKEMON DETAILS
GET {{SERVER}}pokemon/1


### CREATE POKEMON
POST {{SERVER}}pokemon/create
Content-Type: application/json

{
  "name": "diglet",
  "type": "water"
}


### CREATE POKEMON
PUT {{SERVER}}pokemon/1/update
Content-Type: application/json

{
  "name": "hardy1",
  "type": "water"
}


### DELETE POKEMON
DELETE {{SERVER}}pokemon/1/delete
