### SERVER
@HOST = http://localhost:8080
@VERSION = /api/
@SERVER = {{HOST}}{{VERSION}}


### GET ALL POKEMONS PAGINATION
GET {{SERVER}}pokemon?pageNo=0&pageSize=10

### GET ALL POKEMONS
GET {{SERVER}}pokemon/all


### GET POKEMON DETAILS
GET {{SERVER}}pokemon/1


### CREATE POKEMON
POST {{SERVER}}pokemon/create
Content-Type: application/json

{
  "name": "diglet",
  "type": "water"
}


### CREATE POKEMON
PUT {{SERVER}}pokemon/1/update
Content-Type: application/json

{
  "name": "hardy1",
  "type": "water"
}


### DELETE POKEMON
DELETE {{SERVER}}pokemon/1/delete



### Register
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "username": "dudu",
  "password": "zile"
}

### login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "dudu",
  "password": "zile"
}
